version: 0.2

env:
  exported-variables:
    - IMAGE_URI

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password | docker login --username AWS --password-stdin "$ECR_REPOSITORY_URL"
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - IMAGE_URI=$ECR_REPOSITORY_URL:$IMAGE_TAG
  build:
    commands:
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - docker push $IMAGE_URI
      - printf '[{"name":"app","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json
      - printf '{"Version":"1.0","ImageURI":"%s"}' $IMAGE_URI > imageDetail.json
      - envsubst < deploy/taskdef.json > taskdef.json
      - cat taskdef.json

artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
    - taskdef.json
